image: node:10

stages:
    - test
    - publish

before_script:
    - npm install

Test Sources
    stage: test
    script:
        - npm run prepush

Publish Sources:
    stage: publish
    only: ['tags']
    script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
        - npm publish

